### ISSUE TITLE
Url to opendreambox git has to be fixed

### ISSUE THREAD

**Issue by jeepcook** [oe-alliance/build-enviroment#49]
Hello,
Currently build image (oatv 7.0) is broken because of a network fail to https://git.opendreambox.org.
The Url seems to have been changed, now it's https://github.com/opendreambox

Error log:
`openatvbuilder70@DESKTOP-EEUVNU2:~/openatv7.0/build-enviroment$ MACHINE=mutant51 DISTRO=openatv DISTRO_TYPE=release make enigma2-image
check internet connection: Online
Loading cache: 100% |#############################################################################################################################################################################| Time: 0:00:01
Loaded 5550 entries from dependency cache.
ERROR: ExpansionError during parsing /home/openatvbuilder70/openatv7.0/build-enviroment/meta-oe-alliance/meta-brands/meta-dream/recipes-bsp/tpm-ca_1.0.bb                                         | ETA:  0:01:18
Traceback (most recent call last):
  File "/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 1196, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f6bde0e38e0>, d=<bb.data_smart.DataSmart object at 0x7f6bde9ffcd0>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)

  File "/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 1605, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f6bde0e38e0>, d=<bb.data_smart.DataSmart object at 0x7f6bde9ffcd0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/lib/bb/fetch2/git.py", line 715, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f6bde0e38e0>, d=<bb.data_smart.DataSmart object at 0x7f6bde9ffcd0>, name='default'):
             """
    >        output = self._lsremote(ud, d, "")
             # Tags of the form ^{} may not work, need to fallback to other form
  File "/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/lib/bb/fetch2/git.py", line 704, in Git._lsremote(ud=<bb.fetch2.FetchData object at 0x7f6bde0e38e0>, d=<bb.data_smart.DataSmart object at 0x7f6bde9ffcd0>, search=''):
                     bb.fetch2.check_network_access(d, cmd, repourl)
    >            output = runfetchcmd(cmd, d, True)
                 if not output:
  File "/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 913, in runfetchcmd(cmd='export PSEUDO_DISABLED=1; export PATH="/home/openatvbuilder70/openatv7.0/build-enviroment/openembedded-core/scripts:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/hosttools"; export HOME="/home/openatvbuilder70"; git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false ls-remote git://git.opendreambox.org/git/tpm-ca.git ', d=<bb.data_smart.DataSmart object at 0x7f6bde0739d0>, quiet=True, cleanup=[], log=None, workdir=None):

    >        raise FetchError(error_message)

bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/openatvbuilder70/openatv7.0/build-enviroment/openembedded-core/scripts:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot/usr/bin/crossscripts:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/sbin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/usr/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/sbin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/tpm-ca/fetcheravoidrecurse-fetcheravoidrecurse/recipe-sysroot-native/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/bitbake/bin:/home/openatvbuilder70/openatv7.0/build-enviroment/builds/openatv/release/hd51/tmp/hosttools"; export HOME="/home/openatvbuilder70"; git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false ls-remote git://git.opendreambox.org/git/tpm-ca.git  failed with exit code 128, output:
fatal: unable to connect to git.opendreambox.org:
git.opendreambox.org[0: 82.149.226.176]: errno=Connection timed out

The variable dependency chain for the failure is: SRCPV -> PV -> BP -> FILESPATH

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:1076: enigma2-image] Error 1
`

**Comment by jeepcook** [comment]
Test to build OATV 6.4 version. Same problem.

**Comment by jbleyel** [comment]
https://git.opendreambox.org is down.
Move to https://github.com/opendreambox will not help because it's not a mirror.

**Comment by BliNeR-KeY** [comment]
lets wait https://git.opendreambox.org be online.
lol

**Comment by jeepcook** [comment]
Ok sorry, I thought to have found a real compilation error... but no... ;-)
Regards

**Comment by BliNeR-KeY** [comment]
> Ok sorry, I thought to have found a real compilation error... but no... ;-) Regards

honestly i thought opendreambox are back online soon but nothing.
if you are compile only HD51 update oea. 

thanks @atvcaptain move in oea  libdvbsi++ and bdremux .
please update oea and delete or edit tpm-ca_1.0.bb in tpm-ca_1.0.bb_ so when or if open dreambox online you remame on tpm-ca_1.0.bb.

**Comment by atvcaptain** [comment]
we have disable dreambox build, now you can build again

**Comment by jeepcook** [comment]
Ok thanks to have considered my request BliNeR-KeY. 
Now build is running. I compile daily for my hd51 and my sf8008, so no need dreambox! 
Thanks for the tip, the dm git is in parallel back online !
